GET http://localhost:3000/api/authors
Content-Type: application/json
###
GET http://localhost:3000/api/books
Content-Type: application/json
###

POST http://localhost:3000/api/authors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjI4ZmI5YTAxNDBjMWNkMGRjZjllM2EiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTM5Nzc3NTgsImV4cCI6MTcxMzk4MTM1OH0.RL8-8ruIr-Ugh6CSgYvBeDCRHtTGHzwwNDR9EwDji2E

{
    "name": "James Bond",
    "Biography": "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sed, repudiandae."
}

###
POST http://localhost:3000/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NjI4ZmI5YTAxNDBjMWNkMGRjZjllM2EiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTM5Nzc3NTgsImV4cCI6MTcxMzk4MTM1OH0.RL8-8ruIr-Ugh6CSgYvBeDCRHtTGHzwwNDR9EwDji2E

{
    "title": "The Catcher in the Rye",
    "author": "James Bond",
    "isbn": "9780316769488",
    "imageUrl": "https://m.media-amazon.com/images/I/51bO+DX2vEL.jpg",
    "price": "15.99",
    "description": "A story about teenage angst and alienation",
    "genre": "Fiction",
    "quantity": "10"
}

###
POST  http://localhost:3000/admin
Content-Type: application/json

{
    "username": "admin",
    "password": "123456",
    "email": "meme@gmail.com"
}

###
POST  http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
POST http://localhost:3000/api/carts/97178e0f-b961-4a53-bee9-e714f85b5af1/items
Content-Type: application/json

{
    "bookId": "662931a4baa1b4d05cd5da14",
    "quantity": 29
}

